### ISSUE TITLE
"extensions" option lost since new versions?

### ISSUE THREAD

**Issue by kud** [postcss/postcss-custom-media#43]
I don't see in the releases the fact you removed the option/attribute "extensions" which I used.

https://github.com/postcss/postcss-custom-media/releases

**Comment by kud** [comment]
By the way, I've tried different styles of import and the only way to make it work is:

```
const customMedia = require("./mediaQueries.json")

require("postcss-custom-media")({
    importFrom: [{ customMedia }],
}),
```

```
require("postcss-custom-media")({
    importFrom: "./mediaQueries.json",
}),
```

didn't work for instance.

**Comment by jonathantneal** [comment]
I’d have to see your `mediaQueries.json` file to know why. I’m guessing that it doesn’t follow the naming pattern.

> JavaScript files, JSON files, functions, and objects will need to namespace custom media using the `customMedia` or `custom-media` key.
> — https://github.com/postcss/postcss-custom-media#importfrom

See the examples in that section for further clarification.

**Comment by kud** [comment]
```
{
  "--mobile": "(max-width: 480px)",
  "--mobile-only": "(max-width: 480px)",
  "--mobile-excluded": "(min-width: 481px)",
  "--tablet": "(max-width: 1024px)",
  "--tablet-only": "(min-width: 481px) and (max-width: 1024px)",
  "--desktop": "(min-width: 1025px)",
  "--desktop-only": "(min-width: 1025px)"
}
```

I use it like this because I've got a component called `MediaQuery` which helps me to handle responsive design with the same definitions that I've got for my CSS (via your plugin).

```
// import styles from "./index.module.css"

import React from "react"
import PropTypes from "prop-types"
import ReactResponsive from "react-responsive"

import { MQ } from "~/constants"

export const isMediaMatched = prop => {
  const query = MQ[`--${prop}`] ? MQ[`--${prop}`] : prop

  return window.matchMedia(query).matches
}

class MediaQuery extends React.PureComponent {
  static propTypes = {
    children: PropTypes.node.isRequired,
    which: PropTypes.string,
  }

  static defaultProps = {
    which: null,
  }

  render() {
    const { which, children, ...rest } = this.props
    const query = which ? MQ[`--${which}`] : null

    return (
      <ReactResponsive query={query} {...rest}>
        {children}
      </ReactResponsive>
    )
  }
}

export default MediaQuery
```

**Comment by jonathantneal** [comment]
That first example looks good, as long as you are passing into a `customMedia` or `custom-media` key on the object being passed into `importFrom`.

If you’re still having issues, could you setup a small project replicating the issue so that I could take a look?

Here is a test we have for this functionality https://github.com/postcss/postcss-custom-media/blob/master/.tape.js#L15-L20

**Comment by kud** [comment]
It's ok, it works with 

```
const customMedia = require("./mediaQueries.json")

require("postcss-custom-media")({
    importFrom: [{ customMedia }],
}),
```

My main issue is that on release tab, we don't see you removed "extensions" attribute, and I had no error when compiling. But when I see my website, `--tablet` wasn't understood and the css rendered badly.

Two ways of improvement, when changing the API:

- Write in the release/CHANGELOG.md that an option/attribute is deleted
- Show a warning during the compilation (for like 1 version , like you can have in React) that `extensions` is not more understood.

Because I had the bad surprise to see that the compilation ran well but the render wasn't good.

**Comment by jonathantneal** [comment]
I’m sorry about that. The API changes were mine.

This plugin broke on minimally complex media queries before v7, and there was no one to update the plugin with me, so I re-wrote it from scratch, along with at least two other plugins. One of the casualties was not understanding and documenting the previous API in some cases, like this one.

I hope future migrations are easier for you, because Custom Media, Custom Selectors, and Custom Properties, and a handful of other plugins now all share the same `importFrom` API moving forward.
